### ISSUE TITLE
[Feature] support config for proxy of api.github.com 

### ISSUE THREAD

**Issue by liangyuanpeng** [giscus/giscus#1000]
I want to config for the `api.github.com` , it's working for the user who can not access `api.github.com`.

Giscus is a great project and thanks for your work.

**Comment by nschonni** [comment]
This app is a wrapper for the GitHub Discussions API, so this doesn't exist without the API, and there is no workaround

**Comment by liangyuanpeng** [comment]
![image](https://user-images.githubusercontent.com/28711504/232197313-772a3bd8-bfc2-47ae-8c9d-327bea2f809d.png)

It happen on you create a comment .

**Comment by nschonni** [comment]
https://github.com/giscus/giscus#how-it-works

**Comment by laymonage** [comment]
Hi, I understand your request, but I don't think this is a good idea to be supported on the giscus.app service. With this feature, web developers can create their own proxy service and easily use (or misuse) the user's GitHub token. As the proxy isn't obvious to users, they might end up thinking the giscus app is responsible for any misuse of the token.

If you would like to have this option, feel free to self-host a fork and change the code so that it points to your proxy.

**Comment by liangyuanpeng** [comment]
> and easily use (or misuse) the user's GitHub token

You're absolutely wright.

@laymonage Thanks for your confim and i'm deploy myself giscus for this case.
