### ISSUE TITLE
[Bug] 404 Discussion Not Found

### ISSUE THREAD

**Issue by brant-ruan** [giscus/giscus#1154]
Hi, 

These days I find the giscus comment zone doesn't appear at the bottom of my blog, which works well before this week. The icon appears and then disappears when I scroll the page downwards to the comment zone.

If there is no discussion for the current post , the console shows as below and doesn't create a new discussion:

<img width="1072" alt="image" src="https://github.com/giscus/giscus/assets/13882906/a8f3dd36-5807-42c5-94f4-2bc1271b61f5">

The request URL is:

https://giscus.app/api/discussions?repo=brant-ruan%2Ffernweh-comments&term=posts%2Fml021-01%2F&category=Announcements&number=0&strict=false&first=15

The blog post is: https://blog.wohin.me/posts/ml021-01/

If I request manually, the giscus.app shows: {"error":"Discussion not found"}.

If the discussion already exists, the manual request could be used to get the discussion content, and there is no error in the console, while the comment zone is still not there.

I checked the configurations for giscus and it seems to be correct. BTW, I am using giscus with Hugo.

Could you please give some suggestions on how to solve this issue?

Thanks,
brant-ruan

**Comment by AntoineSoetewey** [comment]
Hello, I think I have a similar issue. Comments were available last week and now they don’t appear anymore:

![IMG_3931](https://github.com/giscus/giscus/assets/17910063/9742699d-a8ee-4e68-b1f1-e4ad58f38871)

I didn’t change anything since last week. I’m also using Hugo.

Thanks in advance for any insight!

**Comment by laymonage** [comment]
Thank you for the report! This was caused by an issue in Preact v10.17.0 (https://github.com/preactjs/preact/issues/4104) and was fixed in v10.17.1, which was [released just 4 minutes](https://github.com/preactjs/preact/releases/tag/10.17.1) after I updated to v10.17.0 in 588ab3168144d132367dbddc6be379e04ed72f6a. Talk about bad timing...

**Comment by AntoineSoetewey** [comment]
Thanks a lot @laymonage !

**Comment by brant-ruan** [comment]
@laymonage Thanks! 👍
