### ISSUE TITLE
Comments box and timeline taking up all screen width

### ISSUE THREAD

**Issue by Zerodya** [giscus/giscus#1163]
Comments box and timeline expand horizontally to both sides of the screen, taking up all the width available as shown below instead of having empty margins to the sides 

![2023-09-03-205023_hyprshot](https://github.com/giscus/giscus/assets/73220426/0d8e7130-5b9a-477f-8cf4-e0c0350e1e38)

Any idea why that would be? For instance I was using utterances before and didn't have this problem.

**Comment by laymonage** [comment]
The iframe/container always takes the full width of the parent element. If you need to set a width limit, you can set the parent's width or target the iframe/container with `.giscus-frame`/`.giscus` selectors.

Please provide an accessible link where the issue happens, otherwise it's very hard to find where the issue is.

**Comment by Zerodya** [comment]
It should be observable in [this post](https://zerodya.net/hello-world/).

This is the post template I'm using in my website
```
{{!< default}}

<div class="content-area">
    <aside class="gh-sidebar"><div class="gh-toc"></div></aside>
    <main class="site-main">
        {{#post}}
            {{> content width="wide"}}
        {{/post}}
        {{#is "post"}}
            {{#if @custom.show_related_posts}}
                {{> related}}
            {{/if}}
            {{> comment}}
                <script src="https://giscus.app/client.js"
                        data-repo="Zerodya/comments"
                        data-repo-id="R_kgDOHlibvQ"
                        data-category="Announcements"
                        data-category-id="DIC_kwDOHlibvc4CZDfq"
                        data-mapping="title"
                        data-strict="0"
                        data-reactions-enabled="1"
                        data-emit-metadata="0"
                        data-input-position="top"
                        data-theme="dark"
                        data-lang="en"
                        crossorigin="anonymous"
                        async>
                </script>
        {{/is}}
    </main>
</div>
```

**Comment by laymonage** [comment]
I don't really understand how your template system works but the script tag should be somewhere inside the element with the `.kg-canvas` class so that it is placed with the correct grid column

<img width="1797" alt="image" src="https://github.com/giscus/giscus/assets/6379424/f9090ede-7fb4-422a-981c-5580f9aa9ace">

Or, you can also make an empty `<div>` with the class `giscus` in there so the script will know to put the tag there.

Alternatively, you can also add your own styles with the `.giscus` selector in your CSS.

**Comment by Zerodya** [comment]
My bad, I forgot that the template is specific to [Ghost](https://ghost.org/) blog. Anyway thank you for the inputs, I will try to fix it when I find some time and update the issue.

**Comment by Zerodya** [comment]
> Or, you can also make an empty `<div>` with the class `giscus` in there so the script will know to put the tag there.

Thank you, that worked. Solved by adding `<div class="giscus"></div>` in:
```
<article class="single {{post_class}}">
    <header class="single-header kg-canvas">
        <!-- ... ( header content ) ... -->
    </header>
    <div class="single-content gh-content kg-canvas">
        {{content}}
        <div class="giscus"></div> <!-- HERE -->
    </div>
    {{#is "post"}}
        <footer class="single-footer container medium">
            <!-- ... ( footer content ) ... -->
        </footer>
    {{/is}}
</article>
```

For Ghost specifically, this was in `/var/www/mydomain/content/themes/mytheme/partials/content.hbs`
