### ISSUE TITLE
Jekyll plugin

### ISSUE THREAD

**Issue by thecrewmate876** [giscus/giscus#117]
This would be useful for standard Jekyll (Markdown) users (like me) who use Jekyll for blogging and want Giscus to follow Jekyll's blog post layout.

**Comment by SeanKilleen** [comment]
FYI I'm working on integration with the minimal mistakes Jekyll theme: https://github.com/laymonage/giscus/discussions/116

Might be useful as a pointer for integrating with Jekyll -- once I get it to work that is 😅

**Comment by thecrewmate876** [comment]
> 
> 
> FYI I'm working on integration with the minimal mistakes Jekyll theme: #116
> 
> Might be useful as a pointer for integrating with Jekyll -- once I get it to work that is 😅

@SeanKilleen Ok, also I use GitHub's built-in "Hacker" theme.

**Comment by laymonage** [comment]
Thanks for the suggestion. It's been a while since I last used Jekyll. I'm not sure if there's much value in a plugin, as you can just create a partial HTML template that contains the `<script>` tag and just include that partial in your blog post layout. You can lift the data attributes of the script tag to the site's `_config.yml`, but that's only valuable if you're making a theme for others (like the minimal mistakes example above).

I'll think about this later, but this isn't my top priority.

**Comment by SeanKilleen** [comment]
I agree with @laymonage here, a plugin likely doesn't make much sense. 

@thecrewmate876 in this case, you'd want to use an include file for the script and the HTML, and pull the values for the script from the _config.yml file. 

If you would find it helpful, perhaps I could put together a quick stream to do a tutorial on how to make that happen. But in my opinion, it definitely should be done via the standard Jekyll includes process.

**Comment by LazyRen** [comment]
It's pretty easy to use giscus(or utterances) on Jekyll. I have [post] that guides you how to add it if you are interested. I did not migrated to giscus yet, but I will in near future.

[post]: https://lazyren.github.io/devlog/use-utterances-for-jekyll-comments.html

**Comment by laymonage** [comment]
As others have noted, it's not that complicated to create a partial template in Jekyll to add giscus without using a plugin.

If anyone is interested to make a plugin, feel free to do so, but I'm closing this for now.
