### ISSUE TITLE
Problem with large number of comments

### ISSUE THREAD

**Issue by 0lelouch** [giscus/giscus#258]
When there are a large number of comments the page will load slower because of that. I think a good way to resolve this is that by using page numbers like how it is used in [gitment](https://github.com/imsun/gitment) (uses GitHub issues)
![image](https://user-images.githubusercontent.com/92218586/142581078-d1de4a1a-c0ba-4aea-b04a-82cc45e0e922.png)
another way it can be resolved is, by using a load more button like [gittalk](https://github.com/gitalk/gitalk) (uses GitHub issues)
![image](https://user-images.githubusercontent.com/92218586/142581221-002dcfbf-8f6d-491b-ae34-e3a8cb7e1d6f.png)

**Comment by laymonage** [comment]
Do you have an example of such pages where this is a problem? FYI we're already using the "Load more" button. I haven't benchmarked the performance, though. Some parts may be slow because of how I handled the nesting for SWR.

You can see the following on the [homepage](https://giscus.app):


![image](https://user-images.githubusercontent.com/6379424/142593009-a395c4fb-a14e-41ae-8d90-7ce340539f4d.png)

**Comment by 0lelouch** [comment]
@laymonage My bad, I went directly to the end of [giscus.app](https://giscus.app/) page and saw that there is no load more option. I haven't seen the middle part where load more is present.
