### ISSUE TITLE
Giscus iframe is clipped sometimes

### ISSUE THREAD

**Issue by ramottamado** [giscus/giscus#405]
Comment reactions box got clipped if the comment box is placed above the comments
![image](https://user-images.githubusercontent.com/7479638/154461697-8a3873a0-bc00-4a45-9ee2-d3a9f40434aa.png)

However, if the `reply` text box is active, the reactions box won't get clipped.
![image](https://user-images.githubusercontent.com/7479638/154462909-215da397-4df1-4475-80d2-4ae007bfd712.png)

**Comment by ramottamado** [comment]
I tried moving the comment box to the bottom, but now I found that giscus iframe is clipped if I disable the post reactions.

With post reactions enabled:
![Screenshot from 2022-02-17 18-00-59](https://user-images.githubusercontent.com/7479638/154468615-4e9bffa4-acd9-4594-9624-490e02eebfec.png)

With post reactions disabled:
![Screenshot from 2022-02-17 18-00-40](https://user-images.githubusercontent.com/7479638/154468703-a8018ddc-8792-4d08-8ab8-5ab373de7515.png)

Apparently there's some miscalculations for the iframe height if post reactions disabled.

**Comment by laymonage** [comment]
Thanks, fixed. For some reason, outermost margins do not contribute to the parent (`body`)'s height, but it does to the `html`. I could've just targeted the `html` as the point of reference for the overall height of the `iframe`, but I decided to eliminate these margins and add an extra bottom padding if the input position is at the top.

This does mean that there is a bottom padding even when it's not necessary, e.g. when the reply box is open or if there's a reply to the bottommost comment. I think that's a reasonable compromise rather than having a layout shift every time the reactions popup is toggled.
