### ISSUE TITLE
Pathname match

### ISSUE THREAD

**Issue by Mister-Hope** [giscus/giscus#508]
I am serving my site in different locales, some that there should be /a.html and /zh/a.html

my issue is in some links, different urls loads the same discussion.

e.g:

- https://vuepress-theme-hope.gitee.io/v2/zh/guide/get-started/intro.html
- https://vuepress-theme-hope.gitee.io/v2/guide/get-started/intro.html

they both load a discussion https://github.com/vuepress-theme-hope/giscus-discussions/discussions/45

which it’s title is `v2/zh/guide/get-started/intro `

I think nobody would expect this as the default behavior with pathname, so I insist this is a bug and should be fixed.

**Comment by laymonage** [comment]
https://docs.github.com/en/search-github/getting-started-with-searching-on-github/about-searching-on-github

> **Notes:**
> - Currently our search doesn't support exact matching.

---

> I insist this is a bug and should be fixed.

If you have a solution, feel free to send a PR.

**Comment by Mister-Hope** [comment]
I am not familiar with GitHub api,so it will be hard for me to make a pr.

But in my mind, the current logic is

1. Search with pathname in discussion 
2. If there are results, display first one contents
3. If not, create a new discussion when user has any action

I bet if there is an api fetching discussion contents, there should be an api getting it's title. So the new logic should just be:

1. Search with pathname in discussion 
2. If there are results, get the first one title and see if it matches
3. If so use that discussion and display contents
4. If not, create a new discussion when user has any action

Is there any problems in my understanding and the solution in my mind?

**Comment by Mister-Hope** [comment]
This is even worse when I am using long permalink with only a few characters different in a blog site.

All posts(or article) are using the same discussion.

So I think this is not what we can leave until GitHub supports exact search someday, or something we can ignore to speed up showing a discussion list.

**Comment by Mister-Hope** [comment]
Hi, any plans to fix it? Or just "PR welcome"?

Or is there any workaround for me to stick to one discussion per page? Thanks

**Comment by laymonage** [comment]
Thanks for the suggestion, checking for the title after GitHub returns the results does sound like a reasonable solution. There are a few considerations though:
- It adds another query to the process and it's always executed on every request. The current API just relies on GitHub's search, so we only use the search term every time we fetch the discussion's data and don't keep track of the discussion ID. If we have to make sure the title is correct before fetching the comments, this means that the check is always done on every request. To do this effectively, we need to rework the current approach so that the search is only done on first load, and subsequent requests should use the discussion ID instead.
- This might be a breaking change for some users, as the current docs only mention that the mapping is done by searching whether the discussion title ***contains*** (not *exactly* match) the mapping. Maybe we need to make this exact matching optional.

Another solution that I previously thought about is using a hash of the current search term and put it in the body of the discussion. Then, use that as the basis for the search instead of the title. This would definitely require migrating the existing discussions for users, but using a hash is less prone to fuzzy search issues like this.

> Hi, any plans to fix it? Or just "PR welcome"?
> 
> Or is there any workaround for me to stick to one discussion per page? Thanks. It's not acceptable for me to share a same discussion for different page with different language.

I have a day job. I only work on this on the weekends out of passion, unpaid. As much as I would love to fix this, it's not something that I can have concrete plans on. I'd rather not give any estimates rather than giving them and missing them.

> I am not familiar with GitHub api,so it will be hard for me to make a pr.

So yes, you can see that these things take time and effort. It's only been less than 24 hours than my last comment.

If it's "not acceptable" for you, you can always self-host the application, learn how GitHub's API works, and fix the issue on your self-hosted instance. At this rate, I think you'd be able to fix it much faster than I could.

Anyway, for now, you can always use the "specific discussion mapping" to avoid this issue.

<details>
<summary>FYI</summary>

![The truth behind Open Source apps](https://www.commitstrip.com/wp-content/uploads/2014/05/Strip-Vision-Open-source-650-finalenglish.jpg)

</details>

Cheers.

**Comment by Mister-Hope** [comment]
> Hi, any plans to fix it? Or just "PR welcome"?

I am working on open source project too. Doesn't mean to bother you, instead, just wants to make sure that giscus will treat this as a  bug and plan to add this to fix plan. I will just mark some edge case issue as or welcome, and only pick them up again when I finish all the necessary plans and I am spare🤪

**Comment by dannysteenman** [comment]
@Mister-Hope this is something that github should improve in my opinion.

I left some feedback on the `github/feedback` repo: https://github.com/github/feedback/discussions/16503

**Comment by vertxxyz** [comment]
My workaround is to pass my own term and a hash appended to it. That way partial matches also have to match the hash.

I'd note that it seems like github strips most non-word characters and breaks the results into individual parts of the search match.
My previous attempts were to try to add delimiters of some type to the terms I used, but not only did none of the delimiters I like get matched by github search, they were also useless as my terms were broken up as they contained slashes, meaning partial matches could easily happen anyway.

This is what I ended up going with (I used this hash as I'm also writing C#):
```js
term: `${term} ${toHex(toHashCode(term))}`
...

function toHashCode(s) {
    let h = 0, i = s.length;
    while (i > 0)
        h = (h << 5) - h + s.charCodeAt(--i) | 0;
    return h;
}

function toHex(i) {
    let hex = (i < 0 ? i >>> 0 : i).toString(16);
    return hex.length === 8 ? hex : hex.padStart(8, '0');
}
```

**Comment by brycewray** [comment]
@vertxxyz  Understood. Thanks!

**Comment by laymonage** [comment]
Hey all, thanks for the suggestions! I've had a solution in mind for this, I mentioned it in an earlier comment (https://github.com/giscus/giscus/issues/508#issuecomment-1109459156):

> Another solution that I previously thought about is using a hash of the current search term and put it in the body of the discussion. Then, use that as the basis for the search instead of the title. This would definitely require migrating the existing discussions for users, but using a hash is less prone to fuzzy search issues like this.

I think we could make an optional toggle to enable strict matching that works for all existing mapping options. When the toggle is enabled, giscus will search the discussion **body** (instead of title) for the hash of whatever was originally used as the discussion title. The hash can be computed using the built-in [`digest`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest) function in JS Web Crypto API, e.g. with SHA-1 algorithm:

```js
async function digestMessage(message) {
  const msgUint8 = new TextEncoder().encode(message);
  const hashBuffer = await crypto.subtle.digest('SHA-1', msgUint8);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
  return hashHex;
}
```

To migrate, users need to edit the discussions so that the body contains the hash. It should also be possible to write a migration tool that handles this (log in, point to the repo and category, then automatically edit all discussions through the API), but this can be postponed for later.

The truth is, I've been busy preparing to move to another country next month, so I don't have much time to work on this. If the solution turns out to be feasible, maybe I'll put something together this weekend. Thanks for your patience!

**Comment by keenwon** [comment]
Lets users customize the title and body of discussion, as well as the search string

**Comment by keenwon** [comment]
How about creating a label using pathname and then using the label to match?

**Comment by laymonage** [comment]
> How about creating a label using pathname and then using the label to match?

Unfortunately, GitHub's API doesn't support creating/editing discussions with labels yet :( See https://github.com/orgs/github-community/discussions/15431

Good news though: I've implemented this in #621, just need to test it some more and I can merge it.

**Comment by laymonage** [comment]
I've merged it and it's live!

To use strict title matching, add `data-strict="1"` to the `<script>` tag. **However**, you'll need to migrate any existing discussions before using this option. More information can be found on the [docs](https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#data-strict).

In short, you need to edit your discussions' body to include the SHA-1 hash of the title. You can calculate the hash using any SHA-1 calculator, such as [this one](https://xorbin.com/tools/sha1-hash-calculator).

---

For example, for the following discussion:
- #62

The title is `Welcome to giscus!`, so the hash is `cad60a29d1b50cbeb42ec2ff630fc508afb1d2e3`. You can't see it in the discussion body because I've included the hash as an HTML comment, something like:

```
<!-- sha1: cad60a29d1b50cbeb42ec2ff630fc508afb1d2e3 -->
```

Proof:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/6379424/180601940-820901bd-f125-4dd9-817a-d618447829a6.png">


For now, you need to edit your existing discussions to include the hash. New discussions created by giscus will automatically include the hash. Note that you don't need to follow the same format: as long as the hash is there, giscus can find it. For example, if you just write `cad60a29d1b50cbeb42ec2ff630fc508afb1d2e3` in the discussion body, that works too.

**Note that the strict matching is strict, like, really strict.** That means if somehow the search term used by giscus contains a different character, even a whitespace, compared to the actual title you used to calculate the hash on GitHub, it won't match.

I don't think it's worth making an automatic migration tool, as I believe most users only have a handful amount of discussions and it's still reasonable to edit them by hand. If you have **so many** discussions, feel free to change my mind, maybe I can help write a small script.

**Comment by brycewray** [comment]
Thanks **very** much for this effort, @laymonage! 👍 👍

And, just to confirm I have it straight before I try adapting it to my existing discussions: this affects **only** the `data-mapping="title"` choice, correct?

**Comment by laymonage** [comment]
Yep, correct! It works with all existing mapping options (except `number`). It calculates the hash *after* it resolves the mapping into the actual title that will be created for the discussion. The easy way to migrate is to get the SHA-1 of the discussion title that you currently have.

**Comment by brycewray** [comment]
> Yep, correct! It works with all existing mapping options (except `number`). It calculates the hash _after_ it resolves the mapping into the actual title that will be created for the discussion. The easy way to migrate is to get the SHA-1 of the discussion title that you currently have.

Yes, just figured out that part while stumbling around a bit. 😆  Again, many thanks!

**Comment by Hans5958** [comment]
Thanks for the update, sir! It was worth the wait. I expect this to work quite well, and I guess it is going smoothly on my side.

I also have made a script to help myself when adding the hashes. The way to use it is just run the script on any discussion page, and it would do all the job. React pros could help me so it can be by automatically creating "add hash" button or such, but this is fine for me.

```js
document.querySelector('.js-comment-edit-button').click()
var str = document.querySelector('.js-issue-title').textContent.trim()
var buffer = new TextEncoder( 'utf-8' ).encode(str)
var digest = await crypto.subtle.digest('SHA-1', buffer)
var result = Array.from(new Uint8Array(digest)).map( x => x.toString(16).padStart(2,'0') ).join('')
// document.querySelector('.gh-header-show .color-fg-muted').innerHTML += ` &lt;!-- sha1: ${result} --&gt;`
document.querySelector('textarea').innerHTML += `\n\n&lt;!-- sha1: ${result} --&gt;`
document.querySelector('.comment-form-actions .btn-primary').click()
```
