### ISSUE TITLE
og:title does a partial match instead of exact match

### ISSUE THREAD

**Issue by Lusito** [giscus/giscus#601]
I have noticed, that when the title matches partially, it will return that result.
For example:
- If I have a page with og:title set to `I love Lego`
- And there exists a discussion for it, it shows that correctly.
- But if I also have a page called `Remember: I love Lego` or `I love Lego very much`, it will find the discussion for the first page.

There is probably a partial matching going on (the option text "contains" seems to aim at this).
I'd like to disable that if possible, so that it only finds exact matches.

Thanks for this project!

**Comment by laymonage** [comment]
I've added an option to use strict title matching, add `data-strict="1"` to your `<script>` tag to enable this. Note that you'll have to migrate any existing discussions in order to use this option. (You don't have to do this for new discussions).

See https://github.com/giscus/giscus/issues/508#issuecomment-1193106139 for more details.

**Comment by Lusito** [comment]
Hi @laymonage,

I just tried this option and old posts don't get recognized anymore for some reason. Trying to create a new comment creates a new discussion with an exact title match, but it actually shows up when reloading the page.

Do you check for more than the og:title against the discussion title?

Reference: https://github.com/Lusito/blog/discussions

**Comment by laymonage** [comment]
@Lusito yes, please see the comment right above yours.
