### ISSUE TITLE
Way of changing the link pointing back to the original page

### ISSUE THREAD

**Issue by clarkezone** [giscus/giscus#628]
I have giscus installed and working in a test environment.  One problem I anticipate is that gisgus is embedding a link back to the post that originated the comment in every comment stored in the git discussion thread and there is no way of updating this for all posts eg for the case where the domain i'm hosting the blog changes (eg if I want to update the subdomain at some point).  As a workaround, i then wondered if it's possible to configure a URL shortener scheme so that the link pointing back could be indirected through a URL shortener.  would be great if you could either provide a setting / tool to point a set of comments to a new origin URL or alternatively a means of using an indirection like URL shortner.

**Comment by laymonage** [comment]
What do you think about the following idea:
- Instead of the URL returned by `window.location.href`, giscus gets the "back link" from an element on your site, e.g. a custom `<meta name="giscus:backlink">` tag and use that when creating a new discussion.
- You can set the link to use your own URL shortener, which means you'll be able to update the redirect however and whenever you want. As long as the shortened URL remained the same, the link in the discussion created by giscus will still work.

If that sounds like a solution, I can try implementing it.

**Comment by clarkezone** [comment]
That sounds like a smart solution, I like it and it would unblock me in the short term.

**Comment by laymonage** [comment]
Implemented in #642, see: https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#giscusbacklink

**Comment by clarkezone** [comment]
Starting to test this now.
