### ISSUE TITLE
Refused to frame 'https://giscus.app/' .... "frame-ancestors 'self'".

### ISSUE THREAD

**Issue by dragoncoder047** [giscus/giscus#721]
I'm trying to use Giscus on [my blog](https://dragoncoder047.github.io/blog) and the giscus comments frame refuses to load. Chrome gives this error message: `Refused to frame 'https://giscus.app/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".` Is this a config problem on my end, or a Giscus server issue?

**Comment by dragoncoder047** [comment]
Additionally, Giscus gives this error message: `[giscus] An error occurred. Error message: "Unexpected end of JSON input". Session has been cleared.`

This is confusing because there was never any session to begin with. What is going on?

**Comment by laymonage** [comment]
https://github.com/dragoncoder047/blog/blob/88f108af2670185e1ac445c43627149e3fc33e71/p/2022/test-post.html#L110

You specified an incorrect value for `data-lang`. There's no `en_us` language on giscus, only `en`.

**Comment by dragoncoder047** [comment]
Ah. I was using my site's DEFAULT_LANG in the template (https://github.com/dragoncoder047/pelicantheme/blob/2cf0763/templates/giscus.html#L11). I totally did not expect that was the problem. It works now!

Strange how that would cause a frame to refuse to load. SHould this issue stay open?

**Comment by laymonage** [comment]
Glad that it works!

> Strange how that would cause a frame to refuse to load.

Specifying an incorrect language means that the generated link will lead to a 404 page. Only the widget page with the correct origin (according to `giscus.json`) is allowed to be in an iframe.

> SHould this issue stay open?

I don't think so, but I'll see if I can make the error message clearer.

**Comment by drok** [comment]
For posterity, I got this problem by setting the "lang" attribute of the script element dynamically to `navigator.language`, which is the ISO language-locale (a string like `en-US`). This caused the widget URL to be "https://giscus.app/`en-US`/widget?...", and the server responded with 404

I had to truncate the ISO language code to just the first two characters (the language, without locale) with `navigator.language.slice(0, 2)` - then the `/en/` path fragment was used in the URL and the server responded with 200.

I think not supporting ISO language codes is an avoidable heartache. While your server is unable to handle 'en-US', this string is not ambiguous nor incorrect. The server ought to accept the complete, ISO standard language string, even if you have no use for the locale info (why not??)

In any case, returning a '404', which results in a blank IFRAME is hardly user friendly. The `frame-ancestors 'self'` policy on 404 is wrong - the error should be visible to the user.

Also wrong is the "404" message - you clearly understand (as shown [above](#issuecomment-1266401151)) that the problem is "unsupported language". The "404" message should indicate exactly that - "Unknown language" or similar, and not a generic 404.

## I think this bug should be reopened and the problem fixed properly:
  * Implement a proper error message for unsupported languages
  * don't return the `frame-ancestors 'self'` policy on **any** response - it's not appropriate, given your intended use.
