### ISSUE TITLE
Configurable comment sorting

### ISSUE THREAD

**Issue by phil-opp** [giscus/giscus#75]
Hi, I just saw this project and it looks great!

GitHub Discussions supports different sort orders for replies: newest/oldest/top first. This is configurable via buttons (on the right):

![image](https://user-images.githubusercontent.com/1131315/118396266-0f484c00-b64f-11eb-8fd5-18d6365e3212.png)

It would be great if these buttons would be also available on the embedded giscus form. Also, it would be cool if we could configure the default sort order for the comment form, e.g. via the javascript init function.

Right now it looks like giscus only supports oldest first ordering. Would it be possible to add custom orderings or is this not supported by GitHub's dicussion API?

**Comment by laymonage** [comment]
Hi @phil-opp, thanks for the suggestion! Yeah, this has been on my radar since they added the feature (last month I think).

Unfortunately, it seems that this is not yet supported by the API. If you look at the [`Discussion`](https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions#discussion) type, the `comments` field is a `DiscussionCommentConnection!` that only accepts `after`, `before`, `first`, and `last` as the arguments.

Normally, if ordering is supported, there's also an `orderBy` argument that can be used to specify the ordering. An example is the query for [`discussions`](https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions#repositorydiscussions) itself (not the comments).

Now that I think about it, it might be possible to at least implement the Newest ordering by:

- using `last` and `before` instead of `first` and `after` for the front and subsequent pages; and
- using `first` for the last page; then
- reversing the returned results

However, it feels a bit unnatural to do it this way. If someone wanted to try to implement this I would consider it. Otherwise, I think I would wait until the API supports `orderBy`.

**Comment by phil-opp** [comment]
Thanks a lot for the explanation! I agree that waiting for official API support is probably best.

**Comment by laymonage** [comment]
Reversing the comments order is now somewhat possible with a CSS hack using flex box ordering.

For demonstration, the custom CSS example (https://giscus.app/themes/custom_example.css) can do this. Try entering it in the https://giscus.app, or here's a [direct URL for the widget](https://giscus.app/widget?origin=https%3A%2F%2Fgiscus.app%2F&session=&theme=https://giscus.app/themes/custom_example.css&reactionsEnabled=1&emitMetadata=0&repo=laymonage%2Fgiscus&repoId=MDEwOlJlcG9zaXRvcnkzNTE5NTgwNTM%3D&category=&categoryId=MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyNzk2NTc1&description=A+comments+widget+built+on+GitHub+Discussions.&term=Welcome+to+giscus%21).

See my comment on #157  for more details.

**Comment by laymonage** [comment]
Comments can now be sorted using the new buttons interface just like on GitHub. Only Oldest/Newest orderings are available as GitHub has yet to add ordering support in the API. This implementation is done in client-side by reversing the array.

**Comment by phil-opp** [comment]
Thanks a lot for implementing this! Is there a way to set the default order to newest first, e.g. via some `data-` attribute in the script tag?

**Comment by laymonage** [comment]
@phil-opp would tying it to `data-input-position` work for your use case? So, if `data-input-position="top"`, then the comment box will be shown at the top and the default comment order is newest first, and vice versa.

Honestly, I'd like to keep the data attributes to a minimum, so that the onboarding config isn't too overwhelming. I can still consider to add a default order setting in `giscus.json` if you really need the config to be that granular.

**Comment by phil-opp** [comment]
Changing it together with the input position would be a bit surprising I think. I'm also not sure if I want to move the input box to the top, my fear is that more people would comment without looking for their answer in the other comments first. So I would prefer a separate setting for this in the `giscus.json`. However, this isn't really high priority for me right now. I'm fine with delaying this until GitHub adds a proper API for sorting, as my preferred ordering would be "Top" anyway.

**Comment by laymonage** [comment]
Okay, I added `defaultCommentOrder` setting to `giscus.json`. See [the docs](https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#defaultcommentorder) for more details. Not sure they'll update the GraphQL API any time soon though 🫤

**Comment by phil-opp** [comment]
Thanks a lot!

**Comment by laymonage** [comment]
Yeah, but I'm not too keen on adding too many configurations via `data-` attributes, especially for insignificant things like this one since switching the order is just one click away.

**Comment by ryanwwest** [comment]
I hope they'll add this to Github's API, as sorting by top would be very valuable as a post's comment log grows and would bring it much closer to feature parity with something like Reddit posts (tracking for this is [here](https://github.com/orgs/community/discussions/15432#discussion-4028726). I wonder if it would be feasible to do the top sorting on the client-side in the meantime, that can be an O(n*logn) operation so possibly not too intensive?

**Comment by AbhiVarde** [comment]
Hello Sir, Is there a way to configure Giscus to display comments in newest-to-oldest order by default within a Next.js application? Currently, the option seems limited to "oldest to newest." If not natively supported, are there any recommended workarounds?

**Comment by smeijer** [comment]
I know it's an old ticket, but having this as a data attribute would be great imo.

**Comment by giner** [comment]
I'd live to see this feature being a `data-` attribute. It's not just something to be frequently used, I'm inclined to believe that the reversed order (newest first) are useful in more cased than the normal order. For example this is the case for comments under frequently updated docs, the most useful comments will be the newest while older ones could be outdated or misleading.
