### ISSUE TITLE
White background appearing comment section in dark themes

### ISSUE THREAD

**Issue by ameliacode** [giscus/giscus#933]
**Describe the bug**
https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1

If you scroll down all the way to comments section,
comments section has white background..

From what I remember, this error appeared recently in latest updates..
also, the width shrank too.

**Expected behavior**
dark background in dark theme!!

**Screenshots**
[Here's the link](https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1)

**Comment by laymonage** [comment]
The default CSS file has been moved to a separate file instead of an inline element in the HTML to help CSP compatibility.

If you're using that template, you need to update this line:

https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/a03d358ef9bffeaa6e6bc8c32ad038cb3e9334be/next.config.js#L9

to include `giscus.app`, e.g.

`style-src 'self' 'unsafe-inline' giscus.app;`

**Comment by ameliacode** [comment]
unfortunately this didn't worked.. 
This is frustrating..

**Comment by ameliacode** [comment]
Wow thanks a lot. My log seemed perfect in dashboard. It turned out next.config.json didn't reflected properly in vercel.
I just added console.log and worked great 

```
 async headers() {
    console.log(ContentSecurityPolicy)  // this line
    return [
      {
        source: '/(.*)',
        headers: securityHeaders,
      },
    ]
  },
```
I am closing this now 
thanks again
