### ISSUE TITLE
Dark mode doesn't work in custom themes

### ISSUE THREAD

**Issue by Twixes** [giscus/giscus#952]
Giscus is awesome… but I have one problem: `prefers-color-scheme` doesn't seem to work in custom themes (i.e. those loaded from outside of `giscus.app`). See this page for an example: https://matloka.com/blog/essential-macos-only-apps-for-2023
I've literally tried using the exact content of https://giscus.app/themes/preferred_color_scheme.css – this theme works perfectly when specified as `data-theme="preferred_color_scheme"`, but is oblivious to `prefers-color-scheme: dark` as `data-theme="https://matloka.com/assets/giscus.css"`.

**Comment by laymonage** [comment]
Your CSS file is invalid:

https://matloka.com/assets/giscus.css

The `;` here is making the browser ignore the rest of the `(prefers-color-scheme:dark)` query:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/6379424/227726540-5bfb7521-f843-4200-a684-b15fe2f86c45.png">

I removed that semicolon and it works as expected:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/6379424/227726622-072ea3c2-53b7-4b20-bc36-8a5cc8a7dc93.png">

Don't know what causing it as you use sass to generate it, but I noticed Stylelint complained that you don't wrap the URL inside `url()` in quotes, e.g. `url(http://...)` and not `url('http://...')`. Maybe that causes the issue with the compiled CSS, maybe not, but the problem is not on giscus' side.

**Comment by Twixes** [comment]
Oh wow, so looks like it's a Sass bug! Damn semicolons. Well, I removed the "MIT License" comment preceding the dark mode portion (while leaving the file-wide one before the light mode portion), and now Sass makes no fuss. Thanks for catching this!
